package: headless
version: 1.1.0
author: Jelle Schutter
supportpage: https://github.com/jelleschutter/redaxo_headless/issues

page:
    title: 'translate:headless'
    icon: rex-icon fa-bath
    subpages:
        config:
             title: 'translate:headless_config'

requires:
    packages:
        yrewrite: '^2.6'